version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/sendnreceive-app"
    schedule: { interval: "weekly" }
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "weekly" }
