name: CI
on: [push, pull_request]

# Prevent duplicate runs on same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
      - name: Install deps (mobile)
        run: npm ci --prefix sendnreceive-app || npm install --prefix sendnreceive-app
      - run: npm run -C sendnreceive-app lint --if-present
      - run: npm run -C sendnreceive-app test --if-present
